server:
  port: 8989
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/test_springsecurity?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: rahul
      password: password

logging:
  level:
    root: info

